version: "3.8"

services:
  anvil-uplink:
    restart: always
    container_name: anvil-uplink
    build:
      context: .
    environment:
      - ANVIL_UPLINK_KEY=********************************************* # key value hidden for security reasons
      - MODEL_DIR=/models
    volumes:
      - ./models:/models:ro
  anvil-uplink-tx:
    restart: always
    container_name: anvil-uplink-tx
    build:
      context: .
      dockerfile: Dockerfile.tx
    environment:
      - ANVIL_UPLINK_KEY=********************************************* # key value hidden for security reasons
      - MODEL_DIR=/models
    volumes:
      - ./models:/models:ro
